blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://tkirch.dev/forum/board/24-common-passwords/
    about: Official forum.
  - name: Lexicon
    url: https://tkirch.dev/lexicon/lexicon/29-common-passwords/
    about: Official lexicon.
  - name: Website
    url: https://tkirch.dev
    about: Website of Titus Kirch.
  - name: Discord
    url: https://discord.tkirch.dev
    about: The official discord server of Titus Kirch.
